apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "nats-jwt-operator.fullname" . }}-manager-role
  labels:
  {{- include "nats-jwt-operator.labels" . | nindent 4 }}
rules:
- resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nats.deinstapel.de
  resources:
  - natsaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nats.deinstapel.de
  resources:
  - natsaccounts/finalizers
  verbs:
  - update
- apiGroups:
  - nats.deinstapel.de
  resources:
  - natsaccounts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nats.deinstapel.de
  resources:
  - natsoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nats.deinstapel.de
  resources:
  - natsoperators/finalizers
  verbs:
  - update
- apiGroups:
  - nats.deinstapel.de
  resources:
  - natsoperators/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nats.deinstapel.de
  resources:
  - natsusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nats.deinstapel.de
  resources:
  - natsusers/finalizers
  verbs:
  - update
- apiGroups:
  - nats.deinstapel.de
  resources:
  - natsusers/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "nats-jwt-operator.fullname" . }}-manager-rolebinding
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: nats-jwt-operator
    app.kubernetes.io/part-of: nats-jwt-operator
  {{- include "nats-jwt-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "nats-jwt-operator.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "nats-jwt-operator.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'